export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'

export const CREATE_MOVIE_REQUEST = 'CREATE_MOVIE_REQUEST'
export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS'
export const CREATE_MOVIE_ERROR = 'CREATE_MOVIE_ERROR'

export const UPDATE_MOVIE_REQUEST = 'UPDATE_MOVIE_REQUEST'
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS'
export const UPDATE_MOVIE_ERROR = 'UPDATE_MOVIE_ERROR'

export const REMOVE_MOVIE_REQUEST = 'REMOVE_MOVIE_REQUEST'
export const REMOVE_MOVIE_SUCCESS = 'REMOVE_MOVIE_SUCCESS'
export const REMOVE_MOVIE_ERROR = 'REMOVE_MOVIE_ERROR'

export const FETCH_SINGLE_MOVIE_REQUEST = 'FETCH_SINGLE_MOVIE_REQUEST'
export const FETCH_SINGLE_MOVIE_SUCCESS = 'FETCH_SINGLE_MOVIE_SUCCESS'
export const FETCH_SINGLE_MOVIE_ERROR = 'FETCH_SINGLE_MOVIE_ERROR'
